name: NPM - Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  Branches: master
  MainBranch: master
  NPMRegistry: https://registry.npmjs.org/
  InstallCommand: npm ci
  DeployCommand: npm run deploy
  Organization: ProjectArchetype
  Repository: gatsby-hello-world
  Output: /
